## Excepciones

A veces nos podemos encontrar con errores de ejecución en nuestro código y debemos de estar prevenidos. Pueden ser debidos a errores del código y como programadores los iremos corrigiendo, mejorando así la calidad del código.  

También hay errores que se pueden producir por circunstancias externas, como por ejemplo cuando no podemos acceder a un archivo, o cuando hay un problema de acceso a la red que no está disponible. Son lo que se conoce como **errores de tiempo de ejecución** (**Runtime errors** en inglés) y un buen programa siempre tiene que estar protegido contra ellos.

También es necesario proteger nuestros programas contra  el mal uso de los usuarios, que pueden ser mal intencionados o por despiste.

No hay que confundir estos errores con los errores de sintaxis por código mal formado. Existe un mecanismo para tratar estos errores en tiempo de ejecución, cuando nuestro programa se está ejecutando.

Cuando se produce un error de estos, decimos que se genera una **excepción**, y cuando se produce una nuestro programa se detiene en esa línea y se para.

Podemos hacer que nuestro código capture estas excepciones y así evitar que nuestro programa finalice. Para ello usaremos la estructura **try: ... except :**, que se divide en 2 partes, a las que llamaremos bloques:

* Ponemos **try:** antes de la parte inicial donde pensamos que se puede producir la excepción. 
* Ponemos **except:** para indicar el código que queremos que se ejecute si se produce la excepción.

Para delimitar claramente el código de cada parte añadimos unos espacios (normalmente 4) antes de las líneas de código de cada bloque.

Python no utiliza delimitadores para indicar los bloques de código como otros lenguajes (**{...}** en C, C++ o Java), si no que la indentación de las líneas (los espacios iniciales), marca estos bloques.


```python
# Comprobar si una cadena es o no un número
s = input('Introduzca un número  entero: ')
try: # Comienzo del bloque try
    valorInt = int(s)  # Se produce una excepción
    print('Es entero') # Esta línea no se ejecuta
except: # Comienzo del bloque except
    print('No es entero')

print('Hemos terminado') # Esta línea no está dentro de los bloques
```

Existen diferentes tipos de excepciones, según el error que se produzca. Las que se generan por conversión decimos que son de tipo **ValueError**

Vamos a depurar este ejemplo para ver cómo se produce el error paso a paso. Para ello usaremos también la opción de "Entrando" del menú de depuración

![Depuración Thonny Entrando](./images/DepuracionThonnyEntrando.png)

O podemos hacer que entre dentro de la ejecución de una línea que puede ser una función o puede ser un código un poquito más complejo usando la opción **entrando**.

```python
nombre = input('¿Cómo te llamas? ')
print(f'Hola {nombre}')
strEdad = input('¿Cuantos años tienes? ')

try:
    edad = int(strEdad)
    cadena = f'Tienes {edad} años y naciste en el año {2021 - edad}'
    print(cadena)
except:
    print('Se ha producido un error en la conversión')

print('Adios')

```

[![Vídeo: Excepciones en conversiones entre distintos tipos  de variables en Python](https://img.youtube.com/vi/DCtZpmZ8EA8/0.jpg)](https://drive.google.com/file/d/1d33-WJ5v22TSfdLP59SYDqcfEuL2u-xC/view?usp=sharing)

[Vídeo: Excepciones en conversiones entre distintos tipos  de variables en Python](https://drive.google.com/file/d/1d33-WJ5v22TSfdLP59SYDqcfEuL2u-xC/view?usp=sharing)

También podemos lanzar una excepción si se ha producido un error ¿Por qué lanzar una excepción en lugar de hacer algo para corregirlo? porque quizás no está en nuestra mano el evitar el error.

Imagina que hemos hecho un código que calcula el precio de la cuota de una hipoteca y que nos piden que lo hagamos para un importe con valor negativo, para el que claramente no tiene sentido. Si no podemos volver a pedir que nos proporcionen un valor correcto podemos lanzar una excepción indicando el error en los valores proporcionados.

Para hacerlo usaremos la palabra reservada **raise** seguida de **Exception** a la que le podemos pasar un texto explicativo. Por ejemplo, si queremos hacerlo en el caso anterior del cálculo para un capital negativo haríamos:

```python
## Comprobamos que el valor no es válido
raise Excepcion('El capital debe ser mayor que 0')
```

Cuando lanzamos una excepción, en alguna parte del programa se tendrá que capturar (con un try/except) o de lo contrario el programa se detendrá.

